name: CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Run tests
        run: python -m unittest
